// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Pg2RFq1mPHijX7qlr4B6e4v9u21eUTE',
    appId: '1:123269417542:web:fe6da5e8de869ddb1a1847',
    messagingSenderId: '123269417542',
    projectId: 'uniconnect-7e8dc',
    authDomain: 'uniconnect-7e8dc.firebaseapp.com',
    storageBucket: 'uniconnect-7e8dc.appspot.com',
    measurementId: 'G-L78Q75G4GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5DcxPyQnQMC9A-jQl_UfyRNFIw-nwcuk',
    appId: '1:123269417542:android:c634bdfafcff5e451a1847',
    messagingSenderId: '123269417542',
    projectId: 'uniconnect-7e8dc',
    storageBucket: 'uniconnect-7e8dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuzVnP4wI40MXO9Ta4Cl3eiOEH5QaiSaM',
    appId: '1:123269417542:ios:8850cf9efdcbc8c41a1847',
    messagingSenderId: '123269417542',
    projectId: 'uniconnect-7e8dc',
    storageBucket: 'uniconnect-7e8dc.appspot.com',
    iosClientId: '123269417542-3cel8i658tms5hqn90uu0s3o22slbf9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniconnect',
  );
}
